=== holovser/xml/schema/schema.dtd
<!ELEMENT country (name+, introduction+, geography+, people+, government+, economy+, communications+, military+, transportation+ )>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT introduction (#PCDATA)>
        <!ELEMENT geography (#PCDATA|location|coordinates|map-references|area|climate|natural-hazards|population-distribution)* >
        <!ELEMENT people (#PCDATA|population|age-structure|urbanization|distribution)*>
        <!ELEMENT government (#PCDATA)>
        <!ELEMENT economy (#PCDATA|gdp|agriculture|industries|uneployment|balance|budget)*>
        <!ELEMENT communications (#PCDATA|static-telephones|mobile-phones|broadcast-media|internet)*>
        <!ELEMENT military (#PCDATA|forces|obligation|expenditures)*>
        <!ELEMENT transportation (#PCDATA)>

        <!ELEMENT natural-hazards (#PCDATA)>
        <!ELEMENT population-distribution (#PCDATA)>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT coordinates (#PCDATA)>
        <!ELEMENT map-references (#PCDATA)>
        <!ELEMENT area (total?, land?, water?)>
        <!ELEMENT climate (#PCDATA)>
        <!ELEMENT age-structure (category*)>
        <!ELEMENT urbanization (#PCDATA)>
        <!ELEMENT distribution (#PCDATA)>
        <!ELEMENT gdp (#PCDATA)>
        <!ELEMENT agriculture (#PCDATA)>
        <!ELEMENT industries (#PCDATA)>
        <!ELEMENT uneployment (#PCDATA)>
        <!ELEMENT balance (#PCDATA)>
        <!ELEMENT static-telephones (#PCDATA)>
        <!ELEMENT mobile-phones (#PCDATA)>
        <!ELEMENT broadcast-media (#PCDATA)>
        <!ELEMENT internet (#PCDATA)>
        <!ELEMENT budget (#PCDATA)>
        <!ELEMENT forces (#PCDATA)>
        <!ELEMENT obligation (#PCDATA)>
        <!ELEMENT expenditures (#PCDATA)>

        <!ELEMENT category (#PCDATA)>
        <!ELEMENT total (#PCDATA)>
        <!ELEMENT land (#PCDATA)>
        <!ELEMENT water (#PCDATA)>

        <!ELEMENT population (#PCDATA)>

=== holovser/xml/schema/cyprus-transform.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE country SYSTEM "schema.dtd">

<country><name>Cyprus</name><introduction>
    A former British colony,
    Cyprus became independent in 1960 following years of resistance to
    British rule. Tensions between the Greek Cypriot majority and
    Turkish Cypriot minority communities came to a head in December
    1963, when violence broke out in the capital of Nicosia. Despite
    the deployment of UN peacekeepers in 1964, sporadic intercommunal
    violence continued, forcing most Turkish Cypriots into enclaves
    throughout the island. In 1974, a Greek Government-sponsored
    attempt to overthrow the elected president of Cyprus was met by
    military intervention from Turkey, which soon controlled more than
    a third of the island. In 1983, the Turkish Cypriot administered
    area declared itself the "Turkish Republic of Northern Cyprus"
    ("TRNC"), but it is recognized only by Turkey. An UN-mediated
    agreement, the Annan Plan, failed to win approval by both
    communities in 2004. In February 2014, after a hiatus of nearly two
    years, the leaders of the two communities resumed formal
    discussions under UN auspices aimed at reuniting the divided
    island. The most recent round of negotiations to reunify the island
    were suspended in July 2017 after failure to achieve a
    breakthrough. The entire island entered the EU on 1 May 2004,
    although the EU acquis - the body of common rights and obligations
    - applies only to the areas under the internationally recognized
    government, and is suspended in the "TRNC." However, individual
    Turkish Cypriots able to document their eligibility for Republic of
    Cyprus citizenship legally enjoy the same rights accorded to other
    citizens of EU states.
</introduction><geography><location>
    Middle East, island in the
    Mediterranean Sea, south of Turkey; note - Cyprus views itself as
    part of Europe; geopolitically, it can be classified as falling
    within Europe, the Middle East, or both
</location><coordinates>
    35 00 N, 33 00 E
</coordinates><map-references>
    Middle East
</map-references><area><total>9,251
    sq km</total><land>9,241 sq
    km</land><water>10 sq
    km</water></area><climate>
    temperate; Mediterranean
    with hot, dry summers and cool winters
</climate></geography><people><population>
    1,266,676 (July 2020
    est.)
    country comparison to the world:
    157
</population><description/></people><government>
    Country name: This entry includes all forms of the country's
    name approved by the US Board on Geographic Names (Italy is used as
    an example): conventional long form (Italian Republic),
    conventional short form (Italy), local long form (Repubblica
    Italiana), local short form (Italia), former (Kingdom of Italy), as
    well as the abbreviation. Also see the Terminology
    note.

    conventional long form: Republic of
    Cyprus
    conventional short form: Cyprus
    local long form: Kypriaki Dimokratia/Kibris
    Cumhuriyeti
    local short form: Kypros/Kibris
    etymology: the derivation of the name
    "Cyprus" is unknown, but the extensive mining of copper metal on
    the island in antiquity gave rise to the Latin word "cuprum" for
    copper

    note: the Turkish Cypriot community, which
    administers the northern part of the island, refers to itself as
    the "Turkish Republic of Northern Cyprus" or "TRNC" ("Kuzey Kibris
    Turk Cumhuriyeti" or "KKTC")


    Government type:
    This entry gives the basic form of
    government. Definitions of the major governmental terms are as
    follows. (Note that for some countries more than one definition
    applies.): Absolute monarchy - a form of government where the
    monarch rules unhindered, i.e., without any laws, constitution, or
    legally organized opposition. Anarchy - a condition of lawlessness
    or political disorder brought about by the absence of governmental
    authority. Authoritarian - a form of government in whic . . .
    more


    Republic of Cyprus -
    presidential republic; "Turkish Republic of Northern Cyprus"
    (self-declared) - parliamentary republic with enhanced
    presidency

    note: a separation of the two main ethnic
    communities inhabiting the island began following the outbreak of
    communal strife in 1963; this separation was further solidified
    when a Greek military-junta-supported coup attempt prompted the
    Turkish military intervention in July 1974 that gave the Turkish
    Cypriots de facto control in the north; Greek Cypriots control the
    only internationally recognized government on the island; on 15
    November 1983, then Turkish Cypriot "President" Rauf DENKTAS
    declared independence and the formation of the "TRNC,” which is
    recognized only by Turkey


    Capital: This entry gives the name of the seat of
    government, its geographic coordinates, the time difference
    relative to Coordinated Universal Time (UTC) and the time observed
    in Washington, DC, and, if applicable, information on daylight
    saving time (DST). Where appropriate, a special note has been added
    to highlight those countries that have multiple time
    zones.

    name: Nicosia (Lefkosia/Lefkosa)
    geographic coordinates: 35 10 N, 33 22
    E
    time difference: UTC+2 (7 hours ahead of
    Washington, DC, during Standard Time)
    daylight saving time: +1hr, begins last
    Sunday in March; ends last Sunday in October
    etymology: a
    mispronunciation of the city's Greek name Lefkosia and its Turkish
    name Lefkosa, both of which mean "White City"; the Greek name may
    derive from the Greek phrase "leuke ousia" ("white estate")

    Administrative divisions:
    This entry generally gives the
    numbers, designatory terms, and first-order administrative
    divisions as approved by the US Board on Geographic Names (BGN).
    Changes that have been reported but not yet acted on by the BGN are
    noted. Geographic names conform to spellings approved by the BGN
    with the exception of the omission of diacritical marks and special
    characters.

    6 districts; Ammochostos
    (Famagusta); (all but a small part located in the Turkish Cypriot
    community), Keryneia (Kyrenia; the only district located entirely
    in the Turkish Cypriot community), Larnaka (Larnaca; with a small
    part located in the Turkish Cypriot community), Lefkosia (Nicosia;
    a small part administered by Turkish Cypriots), Lemesos (Limassol),
    Pafos (Paphos); note - the 5 "districts" of the "TRNC" are
    Gazimagusa (Famagusta), Girne (Kyrenia), Guzelyurt (Morphou),
    Iskele (Trikomo), Lefkosa (Nicosia)

    Independence: For most countries, this entry gives the date
    that sovereignty was achieved and from which nation, empire, or
    trusteeship. For the other countries, the date given may not
    represent "independence" in the strict sense, but rather some
    significant nationhood event such as the traditional founding date
    or the date of unification, federation, confederation,
    establishment, fundamental change in the form of government, or
    state succession. For a number of countries, the establishment of
    statehood . . . more

    16 August 1960 (from the
    UK); note - Turkish Cypriots proclaimed self-rule on 13 February
    1975 and independence in 1983, but these proclamations are
    recognized only by Turkey

    National holiday:
    This entry gives the primary national
    day of celebration - usually independence day.


    Independence Day, 1
    October (1960); note - Turkish Cypriots celebrate 15 November
    (1983) as "Republic Day"

    Constitution: This entry provides information on a country’s
    constitution and includes two subfields. The history subfield
    includes the dates of previous constitutions and the main steps and
    dates in formulating and implementing the latest constitution. For
    countries with 1-3 previous constitutions, the years are listed;
    for those with 4-9 previous, the entry is listed as “several
    previous,” and for those with 10 or more, the entry is “many
    previous.” The amendments subfield summarizes the process of am . .
    . more


    history: ratified 16 August 1960; note - in
    1963, the constitution was partly suspended as Turkish Cypriots
    withdrew from the government; Turkish-held territory in 1983 was
    declared the "Turkish Republic of Northern Cyprus" ("TRNC"); in
    1985, the "TRNC" approved its own constitution
    amendments: constitution of the Republic of
    Cyprus - proposed by the House of Representatives; passage requires
    at least two-thirds majority vote of the total membership of the
    "Greek Community" and the "Turkish Community"; however, all seats
    of Turkish Cypriot members have remained vacant since 1964; amended
    10 times, last in 2016
    constitution of the “Turkish Republic of Northern Cyprus” -
    proposed by at least 10 members of the "Assembly of the Republic";
    passage requires at least two-thirds majority vote of the total
    Assembly membership and approval by referendum; amended 2014
    (2019)

    Legal system: This entry provides the description of a
    country's legal system. A statement on judicial review of
    legislative acts is also included for a number of countries. The
    legal systems of nearly all countries are generally modeled upon
    elements of five main types: civil law (including French law, the
    Napoleonic Code, Roman law, Roman-Dutch law, and Spanish law);
    common law (including United State law); customary law; mixed or
    pluralistic law; and religious law (including Islamic law). An
    addition . . . more

    mixed legal system of
    English common law and civil law with European law supremacy


    International law organization
    participation: This entry
    includes information on a country's acceptance of jurisdiction of
